### Radded's generic ESP8266 config file ###
# Table:
# -- ENV: Environment variables
# -- HW: Hardware-specific rules
# -- EXT: ESPHome extensions
# -- NET: Networking / AP / Connectivity

# - ENV: Globals - #
esphome:
  name: "PUT A NAME HERE" # TODO: Fill a name
  friendly_name: "PUT A FRIENDLY NAME HERE" # TODO: Fill a friendly name

# - HW: ESP8266 definitions - #
esp8266:
  board: esp01_1m

# - EXT: Enable logging - #
logger:

# - NET: Enable Home Assistant API - #
api:
  encryption:
    key: "PUT YOUR ENCRYPTION KEY HERE" # TODO: Fill an encryption key

# - NET: Enable OTAs - #
ota:
  - platform: esphome
    password: "PUT YOUR OTA PASSWORD HERE" # TODO: Fill an OTA password

# - NET: Wifi information - #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # - NET: Fallback hotspot - #
  ap:
    ssid: !lambda 'return friendly_name + " Fallback Hotspot";'
    password: "PUT YOUR FALLBACK HOTSPOT PASSWORD HERE" # TODO: Fill a fallback hotspot password

captive_portal:

# TODO: - HW: Your device config here - #