### Radded's config file for Bright 34205 White LED A19 ###
# Table:
# -- ENV: Environment variables
# -- HW: Hardware-specific rules
# -- EXT: ESPHome extensions
# -- NET: Networking / AP / Connectivity
# -- HA: Home Assistant entities

# - ENV: Globals - #
esphome:
  name: "PUT A NAME HERE" # TODO: Fill a name
  friendly_name: "PUT A FRIENDLY NAME HERE" # TODO: Fill a friendly name

# - HW: ESP8266 definitions - #
esp8266:
  board: esp01_1m

# - EXT: Enable logging - #
logger:

# - NET: Enable Home Assistant API - #
api:
  encryption:
    key: "PUT YOUR ENCRYPTION KEY HERE" # TODO: Fill an encryption key

# - NET: Enable OTAs - #
ota:
  - platform: esphome
    password: "PUT YOUR OTA PASSWORD HERE" # TODO: Fill an OTA password

# - NET: Wifi information - #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # - NET: Fallback hotspot - #
  ap:
    # No SSID means it should match the device name
    password: "PUT YOUR FALLBACK HOTSPOT PASSWORD HERE" # TODO: Fill a fallback hotspot password

captive_portal:

# - HW: Your device config here - #

# - HA: Monochromatic light entity - #
light:
  - platform: monochromatic
    id: main_light
    name: None
    output: pwm_output
    # - EXT: Light effects - #
    effects:
      - pulse:
          name: "Slow pulse"
          transition_length: 10s
          update_interval: 10s
      - pulse:
          name: "Fast pulse"
          transition_length: 2s
          update_interval: 2s
      - flicker:
          name: "Candlelight"
      - flicker:
          name: "Sparkle"
          intensity: 10%

    # - HW: Restore mode - #
    restore_mode: RESTORE_DEFAULT_OFF

# - HW: PWM output for light on GPIO5 - #
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO5
    frequency: 1000 Hz

# - HA: Status - #
binary_sensor:
  - platform: status
    name: "Status"